import Head from "next/head";
import { useEffect, useState } from "react";

import styles from "@/styles/Home.module.css";
import { socket } from "@/utils/socket";

export default function Home() {
  const [isConnected, setIsConnected] = useState(socket.connected);

  useEffect(() => {
    const onConnect = () => setIsConnected(true);
    const onDisconnect = () => setIsConnected(false);
    const onEvent = (value: string) => console.log(value);

    socket.on("connect", onConnect);
    socket.on("disconnect", onDisconnect);
    socket.on("event", onEvent);

    return () => {
      socket.off("connect", onConnect);
      socket.off("disconnect", onDisconnect);
      socket.off("event", onEvent);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() =>
            socket.emit("message", "This is an event sent from client", (response: string) => {
              console.log(response);
            })
          }
        >
          Send event
        </button>
      </main>
    </>
  );
}
